version: "3"

services:
  chattergun:
    container_name: chattergun
    build:
      context: ./chat
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./chat/nginx.conf:/etc/nginx/nginx.conf
      - ./gun:/var/www/html/gun
      - ./index.js:/var/www/html/index.js
      - ./chat/index.html:/var/www/html/index.html
      - ./chat/style.css:/var/www/html/style.css
    ports:
      - 3300:3000
    depends_on:
      - chattergun-relay

  chattergun-relay:
    container_name: chattergun-relay
    build:
      context: ./relay
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8765:8765