name: 🚀 CI - publish

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  version:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install pnpm
        run: npm i pnpm@latest -g

      - name: Setup npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: Setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: Install dependencies
        run: pnpm install

      - name: Check for uncommitted changes
        id: git-check
        run: |
          if ! git diff --quiet; then
            echo "Uncommitted changes detected, committing them..."
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "chore: commit changes before publishing [skip ci]"
            echo "Changes committed"
          else
            echo "No uncommitted changes, proceeding..."
          fi
      
      - name: Create and publish versions
        uses: changesets/action@v1
        with:
          version: pnpm ci:version
          commit: "chore: update versions [skip ci]"
          title: "chore: update versions [skip ci]"
          publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
